[build]
  command = "npm install --no-save @vitejs/plugin-react && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps --no-optional"
  CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
